### ISSUE TITLE
Make Build wont run

### ISSUE THREAD

**Issue by miamilabs** [clayrisser/docker-openldap#4]
Dear Community,

currently i am strugling to make this project work at my MacBook.

if i run "make build" i get following error : 

```
% make build
tar: Error opening archive: Unrecognized archive format
chmod: /tmp/docker-openldap/.mkpm/mkpm/.bin/mkpm: No such file or directory
./mkpm: line 77: /tmp/docker-openldap/.mkpm/mkpm/.bin/mkpm: No such file or directory
./mkpm: line 77: exec: /tmp/docker-openldap/.mkpm/mkpm/.bin/mkpm: cannot execute: No such file or directory
```

I have attempted a minor workaround by copying the 'mkpm' directory to /tmp/docker-openldap/.mkpm/mkpm/.bin/. However, despite this effort, the build process has been running for an extended duration of 2 hours, even after appending -j 12 to the 'make' command.

System Information:

    Operating System: MacOS M2 (14.1 (23B74))
    Make Version:

```
%: make -v
GNU Make 3.81
Copyright (C) 2006  Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

I would greatly appreciate any assistance, as I have been striving to achieve functional LDAP support for my Postfix setup for the past week, and I had hoped that this LDAP server would offer a viable solution.

Thank you for your consideration and support.

**Comment by clayrisser** [comment]
The Makefiles depend on [GNU](https://www.gnu.org).

I have updated it to give a better error message and prompt you to install the correct tools.

I would recommend installing the following if running this from OSX.

```sh
brew install remake
brew install gnu-tar
brew install coreutils
brew install gnu-sed
brew install grep
```

https://github.com/clayrisser/mkpm

**Comment by clayrisser** [comment]
Make sure git lfs is setup.

```sh
git lfs install
```
